(load "~/.emacs.d/header.el")
(electric-pair-mode 1)
(column-number-mode 1)
(global-hi-lock-mode 1)
(setq-default show-trailing-whitespace t)
(defun set-newline-and-indent ()
(local-set-key (kbd "RET") 'newline-and-indent))
(add-hook 'c-mode-hook 'set-newline-and-indent)
(add-hook 'change-major-mode-hook '(lambda () (highlight-regexp "  " 'hi-blue)))
(setq backup-directory-alist '(("." . "~/.emacs.d/backup")))
(global-set-key (kbd "C-c h") 'header)
